version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

  myapp:
    build: ./db_test
    container_name: myapp
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydatabase
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_ACCESS_KEY: ${AZURE_STORAGE_ACCESS_KEY}
      ADMINKEY: ${ADMINKEY}
      FERNET_KEY: ${FERNET_KEY}
      GOOGLE_MAIL: ${GOOGLE_MAIL}
      GOOGLE_PASSWORD: ${GOOGLE_PASSWORD}

    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  pg_data:
