name: Deploy to Server with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-flask-app:latest -f db_test/Dockerfile db_test
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-flask-app:latest

      # Step 4: SSH into server and deploy the new container
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DOCKER_PORT }}
          debug: true
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-flask-app:latest
            docker stop myapp || true
            docker rm myapp || true
            docker stop postgres_db || true
            docker rm postgres_db || true
            docker run -d --name postgres_db -p 5432:5432 \
              -e POSTGRES_USER=myuser \
              -e POSTGRES_PASSWORD=mypassword \
              -e POSTGRES_DB=mydatabase \
              --restart always \
              postgres:latest
            docker run -d --name myapp -p 8000:8000 --restart always \
              -e DATABASE_URL=postgresql://myuser:mypassword@postgres_db:5432/mydatabase \
              ${{ secrets.DOCKER_USERNAME }}/backend-flask-app:latest
